<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ai_reports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); // Generated by
            $table->string('period'); // 7, 30, 90, 365, all
            $table->timestamp('period_start')->nullable();
            $table->timestamp('period_end');
            $table->unsignedInteger('incident_count')->default(0);
            $table->json('stats');
            $table->json('analysis');
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_reports');
    }
};
